word = input('Enter something:')
print(type(word))
print('Is this a space?', word.isspace())
print('Is this a number?', word.isnumeric())
print('Is this a letter?', word.isalpha())
print('Is this a title?', word.istitle())
print('Is this a identifier?', word.isidentifier())
print('Is this a decimal?', word.isdecimal())
print('Is an alphanum?', word.isalnum())
